// Copyright (c) 2026 ktsu-dev contributors

namespace ktsu.Osculator.Tests.Gallery;

using System.Collections.Generic;
using System.Text;

/// <summary>Writes the gallery's <c>README.md</c>, which captions each picture.</summary>
internal static class GalleryIndex
{
	/// <summary>Renders the index for the given entries, in catalogue order.</summary>
	/// <param name="entries">The entries.</param>
	/// <returns>The index's Markdown.</returns>
	internal static string Render(IReadOnlyList<GalleryEntry> entries)
	{
		StringBuilder text = new();
		text.Append("# Application gallery\n\n");
		text.Append("<!-- Generated by Osculator.Tests/Gallery. Edit GalleryCatalog.cs, not this file. -->\n\n");
		text.Append("Osculator's panels as they draw today, staged and photographed headlessly by the test suite. ");
		text.Append("Every picture is computed from element sets compiled into the application or constructed by the gallery, at fixed epochs rather than the wall clock, ");
		text.Append("and the stopwatch columns read \"hidden\", so the same code always draws the same pictures. ");
		text.Append("They are regenerated after every successful build of `main`.\n\n");

		foreach (GalleryEntry entry in entries)
		{
			text.Append("## ").Append(entry.Name).Append("\n\n");
			text.Append(entry.Description).Append("\n\n");
			text.Append("![").Append(entry.Name).Append("](").Append(entry.Slug).Append(".png)\n\n");
		}

		return text.ToString();
	}
}
